imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
# app/config/config*.yml
# define the parameters in app/config/parameters.yml
propel:
    dbal:
        driver:               pdo_mysql
        user:                 root
        password:             null
        dsn:                  pdo_mysql:host=127.0.0.1;dbname=test;charset=UTF8
        options:              {}
        attributes:           {}
