books:
    path:     /
    defaults: { _controller: "SoftBooksBundle:Books:index" }

books_show:
    path:     /{id}/show
    defaults: { _controller: "SoftBooksBundle:Books:show" }

books_new:
    path:     /new
    defaults: { _controller: "SoftBooksBundle:Books:new" }

books_create:
    path:     /create
    defaults: { _controller: "SoftBooksBundle:Books:create" }
    methods:  POST

books_edit:
    path:     /{id}/edit
    defaults: { _controller: "SoftBooksBundle:Books:edit" }

books_update:
    path:     /{id}/update
    defaults: { _controller: "SoftBooksBundle:Books:update" }
    methods:  [POST, PUT]

books_delete:
    path:     /{id}/delete
    defaults: { _controller: "SoftBooksBundle:Books:delete" }
    methods:  [POST, DELETE]
